### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by schoel-bis** [IJustDev/Gitea-VSCode#11]
This extension looks really very promising indeed. Yet, I am not getting to see the issues or anything. Instead, I am presented with a rather generic "HTTP Error" message. The issue for me may be that I have Gitea running on a sub-path as root, i.e. an address like https://myservername.com/gitea. Running with `code --verbose` it tells me that the configuration cannot be read if I put the `/gitea` part in the domain name configuration. If I make it a part of the repository configuration (like `gitea/myorg/myrepo`) I get a 404. Is there any way to get such a setup too work?

**Comment by IJustDev** [comment]
Thanks for creating this issue.

I think your problem could be solved by modifying following line:

https://github.com/IJustDev/Gitea-VSCode/blob/79d6755e72df69294c8a2cf1f15f6af82d407d76/src/Config.ts#L91

If you don't use SSL, your API-request URL will look like this:
`https://myservername.com/gitea:PORT`

So if you specified a port you can check if it works once clearing out the port field.
Otherwise please reply and I will try to fix it asap.

**Comment by schoel-bis** [comment]
Thanks for taking the time to look into this.

Alright, so that code helped a lot: The problem for me was, that I specified my user account as the repo owner instead of the owning organisation. Since the site is on SSL all was fine once I changed that. I am delighted by the now working extension; this is going to simplify things quite a bit.

It would have helped if the extension had somehow logged the request URL in case of an error or included it in the error message.

Yet, the line you are citing for non-SSL will probably not work with such a setup (i.e. installed to a sub-path) as the colon will still get appended to the path. You will get something like `http://myserver.com/gitea:/api/v1/…`. I am therefore leaving this issue open and leave the decision whether to close it as an irrelevant edge-case to you.

**Comment by IJustDev** [comment]
It's everything else than irrelevant :) Thanks for opening and I'm glad I could help.
* I would suggest throwing an error with following message: "An HTTP error occoured. Please check your repository url."
* Furthermore to fix the case when using an subpath I would try to include a setting for the subpath, or just let the user enter his repository url all at once so that there are no complications anymore with the port setting.

What do you think?

**Comment by schoel-bis** [comment]
I am glad you see it that way. To reply to your suggestions:

* It would have helped me a lot with my problem if the actual URL that caused the failure had been displayed somewhere, possibly along with an HTTP status code, whether in the VSC error popup or on the command line log (what is printed to the underlying terminal if you run VSC with `code --verbose`).

* And I think I would opt for an additional setting for a "URL path to Gitea" or so as I think it is less than obvious if you have to add it to the domain name. After all, it is not a part of the domain name.

Just my 2 cents. Hope it helps a bit.
